//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class idioma
    {
        public int id { get; set; }
        public string translation1 { get; set; }
        public string translation2 { get; set; }
        public string example { get; set; }
        public System.DateTime insert { get; set; }
        public System.DateTime update { get; set; }
        public string gender { get; set; }
        public Nullable<int> langid1 { get; set; }
        public Nullable<int> langid2 { get; set; }
        public string synonym { get; set; }
    }
}
