//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class imagez
    {
        public string BLOBName { get; set; }
        public string caption { get; set; }
        public string description { get; set; }
        public byte[] BLOBimage { get; set; }
        public byte[] BLOBimage_tn { get; set; }
        public string category { get; set; }
        public System.Guid uuid { get; set; }
        public System.DateTime insert_dt { get; set; }
    }
}
