//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class store_price
    {
        public Nullable<int> storeid { get; set; }
        public string product { get; set; }
        public int qty { get; set; }
        public double oz { get; set; }
        public decimal price { get; set; }
        public Nullable<decimal> price_unit { get; set; }
        public Nullable<decimal> price_oz { get; set; }
        public string extra { get; set; }
        public System.Guid uuid { get; set; }
        public System.DateTime insert_dt { get; set; }
    }
}
