//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class qwertyEntities : DbContext
    {
        public qwertyEntities()
            : base("name=qwertyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<article> articles { get; set; }
        public virtual DbSet<encryption> encryptions { get; set; }
        public virtual DbSet<idioma> idiomas { get; set; }
        public virtual DbSet<language> languages { get; set; }
        public virtual DbSet<store_map> store_map { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<imagez> imagezs { get; set; }
        public virtual DbSet<privacy> privacies { get; set; }
        public virtual DbSet<store_price> store_price { get; set; }
    
        public virtual ObjectResult<spGetEncrypt2_Result> spGetEncrypt2(Nullable<int> start, Nullable<int> end)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(int));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetEncrypt2_Result>("spGetEncrypt2", startParameter, endParameter);
        }
    
        public virtual ObjectResult<spGetKey_Result> spGetKey(string lib)
        {
            var libParameter = lib != null ?
                new ObjectParameter("lib", lib) :
                new ObjectParameter("lib", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetKey_Result>("spGetKey", libParameter);
        }
    
        public virtual ObjectResult<spGetPrices_Result> spGetPrices()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetPrices_Result>("spGetPrices");
        }
    
        public virtual ObjectResult<spGetStores_Result> spGetStores()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetStores_Result>("spGetStores");
        }
    
        public virtual int spInsertENC(string msg)
        {
            var msgParameter = msg != null ?
                new ObjectParameter("msg", msg) :
                new ObjectParameter("msg", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertENC", msgParameter);
        }
    
        public virtual int spInsertImagez(string name, string category, string blob, string caption, string desc)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var categoryParameter = category != null ?
                new ObjectParameter("category", category) :
                new ObjectParameter("category", typeof(string));
    
            var blobParameter = blob != null ?
                new ObjectParameter("blob", blob) :
                new ObjectParameter("blob", typeof(string));
    
            var captionParameter = caption != null ?
                new ObjectParameter("caption", caption) :
                new ObjectParameter("caption", typeof(string));
    
            var descParameter = desc != null ?
                new ObjectParameter("desc", desc) :
                new ObjectParameter("desc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertImagez", nameParameter, categoryParameter, blobParameter, captionParameter, descParameter);
        }
    
        public virtual ObjectResult<string> spSelectENC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spSelectENC");
        }
    
        public virtual ObjectResult<spUserLogin_Result> spUserLogin(string userid, string password)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spUserLogin_Result>("spUserLogin", useridParameter, passwordParameter);
        }
    }
}
